### ISSUE TITLE
_() does not work properly

### ISSUE THREAD

**Issue by mykkode** [Pastheme/dpnblog#8]
I installed the plugin and I kept receiving a 500 HTTP error.
I looked in logs and the error is:

PHP Fatal error:  Uncaught Error: Call to undefined function _() in /pastheme/dpnblog/index.php:23

I solved it by removing the _() function, example:

`'label' => _('Categories')`
to 
`'label' => 'Categories',`

**Comment by mykkode** [comment]
Recommendation: add a check for the availability of the function. My guess is that it was disabled by the hosting company due to some security reasons.

**Comment by ynswtf** [comment]
What is server php version. Dpnblog need php version 7.2
